### ISSUE TITLE
get_job_status returns KeyError

### ISSUE THREAD

**Issue by bnewbold** [YelpArchive/python-gearman#13]
I get a KeyError when using get_job_status with a job that has been submitted wait_until_complete=False, though when I try the request again it works:

``` python
>>> import gearman
>>> gc = gearman.client.GearmanClient(['localhost:4730'])
>>> j = gc.submit_job('test', "asdf", wait_until_complete=False)
>>> gc.get_job_status(j)
<GearmanJobRequest task='test', unique='064ac51350d73671ba3aa51086dbb862', priority=None, background=False, state='CREATED', timed_out=False>
>>> # process job
>>> gc.get_job_status(j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/client.py", line 127, in get_job_status
    request_list = self.get_job_statuses([current_request], poll_timeout=poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/client.py", line 141, in get_job_statuses
    return self.wait_until_job_statuses_received(job_requests, poll_timeout=poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/client.py", line 158, in wait_until_job_statuses_received
    self.poll_connections_until_stopped(self.connection_list, continue_while_status_not_updated, timeout=poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/connection_manager.py", line 194, in poll_connections_until_stopped
    self.handle_connection_activity(read_connections, write_connections, dead_connections)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/connection_manager.py", line 160, in handle_connection_activity
    self.handle_read(current_connection)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/connection_manager.py", line 218, in handle_read
    current_handler.fetch_commands()
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/command_handler.py", line 39, in fetch_commands
    continue_working = self.recv_command(cmd_type, **cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/command_handler.py", line 65, in recv_command
    completed_work = cmd_callback(**cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/gearman-2.0.2-py2.7.egg/gearman/client_handler.py", line 151, in recv_status_res
    current_request = self.handle_to_request_map[job_handle]
KeyError: 'H:trurl:1267'
>>> # do nothing, just call the same method again
>>> gc.get_job_status(j)
<GearmanJobRequest task='test', unique='064ac51350d73671ba3aa51086dbb862', priority=None, background=False, state='COMPLETE', timed_out=False>
```

**Comment by eminence** [comment]
This sounds like the issue I worked around in this commit: eminence/python-gearman@ee44fbf533f3c1f8f820f328d163e8f758757a5c

**Comment by bnewbold** [comment]
Thanks, that patch fixes both my example above and the issue I was having with my real code. It seems like there would be a memory leak due to all the old requests hanging around in old_handlers. FWIW this is all running on Ubuntu 11.04 64bit with Python 2.7.1 and gearmand 0.14.

I don't know enough about the gearman protocol enough to know if this is sane, but a more crude solution would be to catch the KeyError in recv_status_res() and just ignore any STATUS_RES packets for which we don't remember the handle. 

I'll leave this ticket open until a non-leaking fix is commited to master?

**Comment by eminence** [comment]
I agree that there is a memory leak, as the old_handles dictionary never gets purged.   I'm not sure how best to clear them out.  Maybe some timer-based mechanism?  I think it's perfectly possible that someone might issue a GET_STATUS long after a job has been completed, so we don't just want to ignore those STATUS_RESs.

**Comment by noamraph** [comment]
I created a new pull request. Since handle_to_request_map is a WeakValueDict, entries can simply be left there, without a memory leak.
